[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["team-ondo <teamondo1234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.82.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
